# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
departments = Department.create([{ name: 'Computer Science and Engineering' }])
lectures = Lecture.create([{ name: 'CSE 4GS. Mathematical Beauty in Rome ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 6GS. Mathematical Beauty in Rome Lab 				', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 5A. Introduction to Programming I ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 7. Introduction to Programming with Matlab ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 8A. Introduction to Computer Science: Java I ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 8B. Introduction to Computer Science: Java II ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 11. Introduction to Computer Science and Object-Oriented Programming: Java ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 12. Basic Data
		  Structures and Object-Oriented Design ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 15L. Software Tools and Techniques Laboratory ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 20. Discrete Mathematics ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 21. Mathematics for Algorithms and Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 30. Computer
		  Organization and Systems Programming ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 80. UNIX Lab ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 86. C++ for Java Programmers ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 87. Freshman Seminar ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 90. Undergraduate Seminar ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 91. Perspectives
		  in Computer Science and Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 99. Independent
		  Study in Computer Science and Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 100. Advanced Data Structures ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 101. Design and Analysis of Algorithms ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 103. A Practical
		  Introduction to Probability and Statistics ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 105. Theory of Computability ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 107. Introduction to Modern Cryptography ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 110. Software
				  Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 112. Advanced Software Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 118. Ubiquitous Computing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 120. Principles
		  of Computer Operating Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 121. Operating
		  Systems: Architecture and Implementation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 123. Computer Networks ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 124. Networked Services ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 125. Software
		  System Design and Implementation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 127. Introduction to Computer Security ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 130. Programming
		  Languages: Principles and Paradigms ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 131. Compiler Construction ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 132A. Database System Principles ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 132B. Database Systems Applications ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 134B. Web Client Languages ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 135. Server-side Web Applications ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 140. Components
		  and Design Techniques for Digital Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 140L. Digital Systems Laboratory ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 141. Introduction to Computer Architecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 141L. Project in Computer Architecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 143. Microelectronic System Design ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 144. Computer-Aided Design of VLSI Circuits ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 145. Embedded System Design Project ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 148. Advanced
		  Processor Architecture Design Project ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 150. Introduction
		  to Artificial Intelligence: Search and Reasoning ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 151. Introduction
		  to Artificial Intelligence: Statistical Approaches ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 152. Introduction to Computer Vision ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 153. Cognitive Modeling ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 160. Introduction to Parallel Computing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 164. GPU Programming ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 165. 3D User Interaction ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 166. Image Processing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 167. Computer Graphics ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 168. Computer Graphics II: Rendering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 169. Computer Animation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 170. Introduction to Human-Computer Interaction Design ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 181. Molecular Sequence Analysis ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 182. Biological Databases ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 184. Computational Molecular Biology ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 190. Topics
		  in Computer Science and Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 191. Seminar in CSE (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 192. Senior Seminar in Computer Science and Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 195. Teaching ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 197. Field
		  Study in Computer Science and Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 198. Directed Group Study (2 or 4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 199. Independent Study for Undergraduates (2 or 4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 199H. CSE Honors Thesis Research for Undergraduates ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 200. Computability and Complexity ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 202. Algorithm Design and Analysis ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 203A. Advanced Algorithms ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 205A. Logic in Computer Science ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 206A. Lattice Algorithms and Applications ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 207. Modern Cryptography ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 208. Advanced Cryptography ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 209A. Topics/Seminar in Algorithms, Complexity,
				  and Logic (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 209B. Topics/Seminar in Cryptography (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 210. Principles of Software Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 211. Software Testing and Analysis ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 216. Research Topics in Human-Computer Interaction ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 218. Advanced
		  Topics in Software Engineering ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 219. Design at Large ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 221. Operating Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 222A. Computer Communication Networks ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 222B. Internet Algorithmics ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 223A. Principles of Distributed Computing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 223B. Distributed Computing and Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 227. Computer Security ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 229A. Topics/Seminar in Computer Systems (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 229B. Topics/Seminar
		  in Networks and Communication (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 229C. Topics/Seminar in Computer Security (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 230. Principles of Programming Languages ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 231. Advanced Compiler Design ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 232. Principles of Database Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 232B. Database System Implementation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 233. Database Theory ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 237A. Introduction to Embedded Computing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 237B. Software for Embedded Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 237C. Validation
		  and Testing of Embedded Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 237D. Design
		  Automation and Prototyping for Embedded Systems ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 239A. Topics/Seminar in Databases (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 240A. Principles of Computer Architecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 240B. Parallel Computer Architecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 240C. Advanced Microarchitecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 240D. Application Specific Processors ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 241A/ECE
		  260B. VLSI Integration of Computing Circuitry ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 242A. Integrated Circuit Layout Automation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 243A. Introduction
		  to Synthesis Methodologies in VLSI CAD ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 244A. VLSI Test ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 245. Computer
		  Aided Circuit Simulation and Verification ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 247. Application Specific and Reconfigurable Computer Architecture ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 248. Algorithmic and Optimization Foundations for VLSI CAD ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 249A. Topics/Seminar
		  in Computer Architecture (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 249B. Topics/Seminar in VLSI (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 249C. Topics/Seminar in CAD (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 250A. Principles of Artificial Intelligence: Probabilistic Reasoning and Learning  ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 250B. Principles of Artificial Intelligence: Learning Algorithms  ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 250C. Machine Learning Theory ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 252A. Computer Vision I ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 252B. Computer Vision II ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 252C. Selected Topics in Vision and Learning (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 254. Statistical Learning ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 255. Data Mining and Predictive Analytics  ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 256/LING 256.
		  Statistical Natural Language Processing ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 258A. Cognitive Modeling ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 259. Seminar in Artificial Intelligence ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 259C. Topics/Seminar in Machine Learning (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 260. Parallel Computation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 262. System
		  Support for Applications of Parallel Computation ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 272. Advanced Image Synthesis ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 274. Selected Topics in Graphics (2–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 280A. Algorithms in Computational Biology ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 282/BENG 202. Bioinformatics II: Sequence and Structure Analysis—Methods and Applications ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 283/BENG 203.
		  Bioinformatics III: Functional Genomics ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 290. Seminar
		  in Computer Science and Engineering (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 291. Topics
		  in Computer Science and Engineering (1–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 292. Faculty Research Seminar ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 293. Special
		  Project in Computer Science and Engineering (1–12)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 294. Research Meeting in CSE ', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 298. Independent Study (1–16)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 299. Research (1–16)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 500. Teaching Assistantship (2–4)', department: Department.find_by_name('Computer Science and Engineering') }, { name: 'CSE 599. Teaching Methods in Computer Science ', department: Department.find_by_name('Computer Science and Engineering') }])
